boipoka/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('boipoka_app.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

boipoka_app/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views
from .forms import *
app_name = 'boipoka_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('notifications/',views.notify_user, name='notifications'),
    path('makeunread/<int:pk>/',views.makeunread, name='makeunread'),
    path('deletenotification/<int:pk>/',views.deletenotifcation, name='deletenotification'),
    path('book_list/',views.book_list, name='book_list'),
    path('books/<int:pk>/', views.book_details, name='book_details'),
    path('create-subscription/<int:pk>/', views.create_subscription, name='create-subscription'),
    path('change_subscription',views.change_subscription, name='change_subscription'),
    path('borrow/<int:pk>/', views.borrow_book, name='borrow_book'),
    path('reading_history/', views.reading_history,name='reading_history'),
    path('report_lost_or_damaged/<int:pk>/', views.report_lost_or_damaged,name='report_lost_or_damaged'),
    path('manage_fines/<int:pk>/', views.manage_fines, name='manage_fines'),
    path('manage_fineapproved/<int:pk>/', views.manage_fineapprove,name='manage_fineapprove'),
    path('mark-as-unread/<int:pk>/', views.mark_unread, name='mark_unread'),
    path('return-book/<int:pk>/', views.return_book, name='return_book'),
    path('reissue/<int:pk>/', views.reissue_book, name='reissue_book'),
    path('add_book/', views.add_book, name='add_book'),
    path('edit_book/<int:pk>/', views.edit_book, name='edit_book'),
    path('delete_book/<int:pk>/', views.delete_book, name='delete_book'),
    path('user_details/<int:pk>/', views.user_details, name='user_details'),
    path('send-returned-notifications/<int:pk>/', views.send_returned_notifications, name='send_returned_notifications'),
    path('send-borrowed-notifications/<int:pk>/',views.send_borrowed_notifications,name='send_borrowed_notifications'),
    path('send_payment_needed/<int:pk>/', views.send_payment_needed,name='send_payment_needed'),
    path('send_payment_approval/<int:pk>/', views.send_payment_approval,name='send_payment_approval'),
    path('reactivesubscription/<int:pk>/', views.reactivesubscription, name='reactivesubscription'),
    path('reissue_grants/<int:pk>/', views.reissue_grant,name='reissue_grant'),
    path('user/send_reminder/<int:pk>/', views.send_reminder, name='send_reminder'),
    path('user/edit_user/<int:pk>/', views.edit_user, name='edit_user'),
    path('user/delete_user/<int:pk>/', views.delete_user, name='delete_user'),
    path('users',views.users,name='users'),
    path('user/update_due_date/<int:pk>/', views.update_due_date, name='update_due_date'),
    path('subscription/',views.subscription, name='subscription'),
    path('new_subscription_creation/',views.new_subscription_creation, name='new_subscription_creation'),	
    path('subscription/renew/', views.renew_subscription, name='renew_subscription'),
    path('user/delete_subscription/<int:pk>/', views.delete_subscription, name='delete_subscription'),
    path('manage_subscriptions_starting/<int:pk>/', views.manage_subscriptions_starting, name='manage_subscriptions_starting'),
    path('manage_subscriptions_ending/<int:pk>/', views.manage_subscriptions_ending, name='manage_subscriptions_ending'),
    path('user/delete_subscription/<int:pk>/', views.delete_subscription, name='delete_subscription'),
    # path('book_details/<int:pk>', views.book_details, name='book_details'),
    # path('add_book/', views.add_book, name='add_book'),
]

boipoka_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from boipoka_app.models import Borrowing, Subscription,Book

FROM_INPUT_CLASSES='text-slate-300 w-full px-5 py-3  rounded-xl border'

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username','email','password1','password2')
    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':"your_name",
        'class':"rounded bg-gray-300 w-full py-1 px-3 !outline-none"
        }))
    email=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':"add_your_email",
        'class':"rounded bg-gray-300 w-full py-1 px-3 !outline-none"
        }))
    password1=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "your_password",
        'class':"rounded bg-gray-300 w-full py-1 px-3 !outline-none"
        }))
    
    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "confirm_your_password",
        'class':"rounded bg-gray-300 w-full py-1 px-3 !outline-none"
        }))
        

class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['subscription_type']  # Assuming 'tier' is the only field you want the user to select

    subscription_type = forms.ChoiceField(choices=Subscription.TIER_CHOICES, widget=forms.Select(attrs={
        'class': "rounded bg-gray-300 w-full py-1 px-3 !outline-none"
    }))
    
    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)
        

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'image','availability_status','total_copies','available_copies']
    title=forms.CharField(widget=forms.TextInput(attrs={'class': FROM_INPUT_CLASSES}))
    author=forms.CharField(widget=forms.TextInput(attrs={'class': FROM_INPUT_CLASSES}))
    description=forms.CharField(widget=forms.Textarea(attrs={'class': FROM_INPUT_CLASSES}))
    image=forms.ImageField(widget=forms.FileInput(attrs={'class': FROM_INPUT_CLASSES}))
    availability_status=forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': FROM_INPUT_CLASSES}))
    total_copies=forms.IntegerField(widget=forms.NumberInput(attrs={'class': FROM_INPUT_CLASSES}))
    available_copies=forms.IntegerField(widget=forms.NumberInput(attrs={'class': FROM_INPUT_CLASSES}))
    
    
# class UpdateDueDateForm(forms.ModelForm):
#     class Meta:
#         model = Borrowing
#         fields = ['due_date']  # Include only the due_date field
#     due_date= forms.DateInput(attrs={'type': 'date'}),  # Set input type to date
#         }

boipoka_app/views.py
from datetime import datetime  # Import datetime for date manipulations
from django.core.mail import EmailMessage  # Import EmailMessage for sending emails
import logging  # Import logging for logging errors and information
from smtplib import SMTPException  # Import SMTPException to handle email sending errors
import threading  # Import threading for sending emails in separate threads
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render, redirect  # Import necessary functions for view handling
from django.contrib.auth import login, authenticate, logout  # Import authentication functions
from django.urls import reverse
import requests  # Import requests for making API calls
from boipoka import settings  # Import project settings
from boipoka_app.utils import get_user_subscription  # Import utility function to get user subscription
from .forms import *  # Import all forms from the current package
from .models import *  # Import all models from the current package
from django.contrib.auth.decorators import login_required, user_passes_test  # Import decorators for access control
from django.contrib import messages  # Import messages framework for user feedback
from django.core.mail import send_mail  # Import send_mail function for sending emails
from django.core.files.base import ContentFile  # Import ContentFile for handling file content
from urllib.parse import urlparse  # Import urlparse for URL manipulation
from django.contrib.auth import get_user_model  # Import function to get User model
import pytz

def is_admin(user):
    """
    Check if the given user is an admin.

    Args:
    user (User): The user object to be checked.

    Returns:
    bool: True if the user is an admin, False otherwise.
    """
    return user.is_staff
def is_not_admin(user):
    """
    Check if the given user is not an admin.

    Args:
    user (User): The user object to be checked.

    Returns:
    bool: False if the user is an admin, True otherwise.
    """
    return not user.is_staff

@login_required
def notify_user(request):
    """
    Handle notifications for a regular user.
    Only accessible if the user is logged in.
    """
    # Fetch all notifications where the subscriber is the current logged-in user
    notifications = Notifications.objects.filter(subscriber=request.user)
    
    # Dictionary to track if notifications are clickable or not
    unclickable = {}
    for notify in notifications:
        # If the notification is read, set its clickable status to False; otherwise, set to True
        if notify.is_read == True:
            unclickable[notify.pk] = False
        else:
            unclickable[notify.pk] = True
    
    # Render the notification template and pass notifications and clickable status used as context
    return render(request, 'boipoka_app/notification.html', {'notifications': notifications, 'unclickable': unclickable})

def index(request):
    return render(request,'boipoka_app/index.html')

@login_required
def makeunread(request, pk):
    # Retrieve the notification object by its primary key (pk) for the logged-in user, or return a 404 error if not found
    notification = get_object_or_404(Notifications, pk=pk)
    
    if notification.subscriber != request.user:
        return HttpResponseForbidden("You are not allowed to access this notification.")
    
    # Mark the notification as read
    notification.is_read = True
    notification.save()
    
    # Redirect the user back to the notifications page
    return redirect('boipoka_app:notifications')

@login_required
def deletenotifcation(request, pk):
    # Retrieve the notification object by its primary key (pk) for the logged-in user, or return a 404 error if not found
    notification = get_object_or_404(Notifications, pk=pk)
    
    # Ensure the notification belongs to the logged-in user
    if notification.subscriber != request.user:
        return HttpResponseForbidden("You are not allowed to access this notification.")
    # Delete the notification from the database
    notification.delete()
    
    # Redirect the user back to the notifications page
    return redirect('boipoka_app:notifications')

def register(request):
    
    # If the request method is POST, process the registration form
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # Save the new user to the database
            login(request, user)  # Log the new user in automatically
            return redirect('/login/')  # Redirect to the login page or another page after registration
        else:
            # If the form is invalid, render the same page with the form errors
            return render(request, 'boipoka_app/register.html', {'form': form})
    else:
        # If the request method is GET, display an empty registration form
        form = CustomUserCreationForm()
    
    # Render the registration template with the form context
    return render(request, 'boipoka_app/register.html', {'form': form})


def fetch_books_data(start_index=0, max_results=10):
    """
    Fetch books data from the Google Books API.

    Parameters:
        start_index (int): The index from which to start fetching books (default is 0).
        max_results (int): The maximum number of books to fetch (default is 10).
    
    Returns:
        list: A list of dictionaries containing book details like title, author, 
            description, image, availability status, total copies, and available copies.
    """
    api_key = settings.GOOGLE_BOOKS_API_KEY
    url = f"https://www.googleapis.com/books/v1/volumes?q=subject:fiction&startIndex={start_index}&maxResults={max_results}&key={api_key}"
    
    # Send a GET request to the Google Books API
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        books = []
        
        if "items" in data:
            for item in data["items"]:
                # Extract volume information and image links from each item
                volume_info = item.get("volumeInfo", {})
                image_url = volume_info.get("imageLinks", {}).get("thumbnail", "")
                image_content = None

                # Fetch image content if available
                if image_url:
                    img_response = requests.get(image_url)
                    if img_response.status_code == 200:
                        # Convert the image response content into a ContentFile
                        image_content = ContentFile(
                            img_response.content, 
                            name=urlparse(image_url).path.split('/')[-1]
                        )
                
                # Append the book's details as a dictionary to the books list
                books.append({
                    "title": volume_info.get("title", ""),
                    "author": ', '.join(volume_info.get("authors", [])),
                    "description": volume_info.get("description", ""),
                    "image": image_content,  # This will be a ContentFile
                    "availability_status": True,
                    "total_copies": 1,
                    "available_copies": 1,
                })
        return books
    
    # Return an empty list if the API call fails or no books are found
    return []

def create_books_in_db(book_list):
    """
    Create or update Book instances in the database based on the given book list.

    Parameters:
        book_list (list): A list of dictionaries, where each dictionary contains details
                        about a book such as title, author, description, image, 
                        availability status, total copies, and available copies.

    For each book in the list:
        - The function checks if a Book instance with the same title already exists in the database.
        - If it exists, it does nothing (leaves the existing record unchanged).
        - If it does not exist, it creates a new Book instance using the provided details.
    """
    for book_data in book_list:
        # Create or update the Book instance in the database
        Book.objects.get_or_create(
            title=book_data['title'],  # Check for an existing book with the same title
            defaults={
                'author': book_data['author'],
                'description': book_data['description'],
                'image': book_data['image'],  # This will save the image file correctly
                'availability_status': book_data['availability_status'],
                'total_copies': book_data['total_copies'],
                'available_copies': book_data['available_copies'],
            }
        )

@login_required
def book_list(request):
    """
    View to display the list of books available for the user.

    - Retrieves the user's subscription information.
    - If the user is not an admin and does not have an active subscription, redirects them to the subscription page.
    - Fetches available books and updates their status based on borrowing and damage history.
    - Suspends the user's subscription if there are unpaid fines for damaged or lost books.

    Parameters:
        request (HttpRequest): The HTTP request object containing metadata about the request.

    Returns:
        HttpResponse: The rendered HTML page displaying the list of books along with their statuses and user-related information.
    """
    # Retrieve the user's subscription
    subscription = Subscription.objects.filter(user=request.user).first()
    
    # If the user is not an admin and does not have a subscription, redirect them to the subscription page
    if is_not_admin(request.user):
        if subscription is None:
            return redirect('boipoka_app:subscription')

    # Get all available books
    books = Book.objects.filter(available_copies__gte=0)
    

boipoka_app/templates/boipoka_app/add_book.html
{% extends 'boipoka_app/base.html' %}
{% block title %}Add New Book{% endblock title %}
{% block content %}
<h2 class='text-white font-bold text-2xl text-center'>Add New Book</h2>
<form method="POST" enctype="multipart/form-data" class="text-white">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="mt-5 py-2 px-8 bg-purple-900 hover:bg-purple-700 rounded-xl  text-white">Add Book</button>
</form>


{% endblock %}

boipoka_app/templates/boipoka_app/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>{% block title %}boipoka{% endblock %}</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> {% endcomment %}
    {% comment %} <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet"> {% endcomment %}
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
</head>
{% comment %} 
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> {% endcomment %}




{% load tz %}
{% load parse_datetime %}
<nav class="-mt-20 fixed  flex items-center w-full px-5 py-5 text-xl text-slate-200  gap-3 justify-center bg-slate-500">
    <button  class="font-bold py-2 px-8 text-white hover:text-indigo-950 "><a href="{% url 'boipoka_app:book_list' %}">Home</a></button>
    {% if request.user.subscription.is_active %}
        {% with subscription=request.user.subscription %}
            {% timezone "Asia/Dhaka" %}
            {% with subscription_endtime=request.user.subscription.subscription_end %}
                {% with subscription_status=subscription_endtime|parse_datetime:"%b. %d, %Y, %I:%M %p" %}
                    {% if subscription_status %}
                        <span class="text-indigo-950 font-bold">Your are a {{ request.user.subscription.subscription_type }} member</span>
                        <span class="text-green-500 font-bold">Your subscription will end on {{ request.user.subscription.subscription_end }}</span>
                        <button class="py-2 px-8 font-bold text-indigo-800 hover:text-indigo-950">
                            <a href="{% url 'boipoka_app:change_subscription' %}?next={{ request.path }}">Change Subscription</a>
                        </button>
                    {% else %}
                        <span class="text-red-500 font-bold">Your subscription has expired.</span>
                        <button class="py-2 px-8 font-bold text-indigo-800 hover:text-indigo-950">
                            <a href="{% url 'boipoka_app:renew_subscription' %}">Renew Subscription</a>
                        </button>
                    {% endif %}
                {% endwith %}   
            {% endwith %}
            {% endtimezone %}
        {% endwith %} 
    {% endif %}

    {% if request.user.is_authenticated %} 
        <form method="post" action="{% url 'boipoka_app:logout' %}">
            {% csrf_token %}
            <button type="submit" class="px-3 py-2 bg-purple-900 hover:bg-purple-700 rounded-xl text-white">Log Out</button>
        </form>
        {% if request.user.is_superuser %}
        <button class=" px-6 py-2 bg-slate-700 text-white font-semibold">
            <a href="{% url 'boipoka_app:add_book' %}">+Add a New Book</a>
        </button>
        <button class=" px-6 py-2 bg-cyan-800 text-white font-semibold">
            <a href="{% url 'boipoka_app:users' %}">Handle User</a>
        </button>
        {% elif request.user.subscription.is_active %}
        <button class=" px-6 py-2 bg-slate-700 text-white font-semibold">
            <a href="{% url 'boipoka_app:reading_history' %}">ReadList History</a>
        </button>
        {% endif %}
        {% if not request.user.is_superuser %}
            <button class=" px-6 py-2 text-white font-bold" style="background-color:#FEBE10 !important;">
                <a href="{% url 'boipoka_app:notifications' %}">Notifications{% if unread_notifications_count %}<sup class="px-3 py-2 font-bold" style="background-color:red !important;color:white !important;border-radius:100% !important;">{{unread_notifications_count}}</sup>{% endif %}</a>
            </button>
        {% endif %}
    {% endif %}
</nav>

<body class='bg-gray-900 '>
    {% block content %}
    {% endblock %}
</body>
</html>

boipoka_app/templates/boipoka_app/book_details.html
{% extends 'boipoka_app/base.html' %}

{% block title %}Book Details{% endblock title %}
{% block content %}
<!--Pop up messages for Some event happend some specific views from where it redirects to this book_details view-->
{% if messages %}
    <div id="popupModal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
        <div class="bg-white rounded-lg shadow-lg max-w-lg w-full">
            <div class="px-6 py-4 border-b border-gray-200 flex justify-between items-center">
                <h5 class="text-xl font-semibold">Attention</h5>
                <button class="text-gray-500 hover:text-gray-700" onclick="closeModal()">
                    &times;
                </button>
            </div>
            <div class="px-6 py-4">
                {% for message in messages %}
                    <p class="text-red-700">{{ message }}</p>
                {% endfor %}
            </div>
            <div class="px-6 py-4 border-t border-gray-200 flex justify-end">
                <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" onclick="closeModal()">Close</button>
            </div>
        </div>
    </div>
    <script>
        function closeModal() {
            document.getElementById('popupModal').style.display = 'none';
        }
    </script>
{% endif %}
<!--Book Image and Description -->
<div class="mt-16 pt-14 flex flex-row  gap-5" >
    <!-- Book Image or Book title if the image is not loaded -->
    <div class="w-full h-full text-white" style="border: 1 px solid !important;">
        {% if book.image %}
            <img src="{{ book.image.url }}" alt="{{ book.title }}" class="w-full h-full"  >
        {% else %}
            <img src="" alt="{{ book.title }}"  class="w-full h-full" >
        {% endif %}
    </div>
    <!-- Book Title and Description  -->
    <div class="p-5 rounded-xl text-dark" style="background-color:#5072A7 !important;">
        <h1><strong class="font-semibold text-3xl">{{ book.title }}</strong></h1>
        {% if book.description %}
        <p class="mt-5 text-xl">
            <span>{{ book.description }}</span>
        </p>
        {% endif %}
        <!-- If User is logged in  -->
        {% if user.is_authenticated %}
            <!-- If the user have subscription -->
            {% if subscription %}
                <!-- Showing the maximum borrowing limit under this subscription -->
                <p class='font-bold'>You can borrow maximum  {{subscription.max_books}} books at once </p>
                <!-- Showing the already borrowed book -->
                <p class='font-bold'>Your have already borrowed  {{ borrowed_books_count }} books </p>
                {% if subscription.max_books >= borrowed_books_count %}  <!--  if the borrowing oppurtunity is remained within the maximum limit  -->
                    <!-- If the book is already borrowed it will be Unavaiable for the user to borrow again  -->
                    {% if not availability %}
                        <div class="flex flex-row items-center justify-between gap-2">
                            <button class="px-2 py-1 mt-5 bg-red-600  text-white">Unavaiable</button>
                            <!-- Book Return Policy  -->
                            <form action="{% url 'boipoka_app:return_book' book.pk %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{% url 'boipoka_app:book_details' book.pk %}">
                                <button type="submit" class="px-3 py-2 bg-orange-500 text-white">Return Book</button>
                            </form>
                        </div>
                    <!-- If the borrowing limit is exceeded -->
                    {% else %}
                        <!-- Here a Flag is used because the borrowing count is updated upon the clicking the Borrow Book button here.
                            As for example for Basic you can borrow 2 books at a time.During 2nd click we will update the Flag to 1,
                            For this reason, if the user attempt to borrow the 3rd time it will show the actions for exceeding the borrowing limit   -->
                        {% if flag == 0 %}
                            <form action="{% url 'boipoka_app:borrow_book' pk=book.pk %}" method="post">
                                {% csrf_token %}
                                <button class="mt-5 px-6 py-2 bg-slate-700 text-white font-semibold" type="submit">Borrow Book</button>
                            </form> 
                        <!-- If the flag is 0 then borrowing is not possible  -->
                        {% else %}
                            <p class="mt-5 text-red-600 font-bold">Sorry, your borrowing limit is exceeded.</p> 
                        {% endif %}
                    {% endif %}
                {% else %}
                    <p class="mt-5 text-red-600 font-bold">Sorry, your borrowing limit is exceeded.</p> 
                {% endif %}
            <!-- If the user doesn't have subscription    -->
            {% else %}
                <!-- If the user is Admin   -->
                {% if user.is_superuser %}
                    <div class="flex flex-row  gap-2 ">
                        <!-- Admin can Edit or Delete the book  -->
                        <button class="mt-5 px-6 py-2 bg-slate-700 text-white font-semibold">
                            <a href="{% url 'boipoka_app:edit_book' book.pk %}">Edit</a>
                        </button>
                        <form action="{% url 'boipoka_app:delete_book' book.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="mt-5 px-6 py-2 bg-red-900 font-semibold text-white">Delete</button>
                        </form>
                    </div>
                {% endif %}
            {% endif %}
            <!-- If the user is not Admin   -->
            {% if not request.user.is_superuser %}
                <div class="flex justify-center text-white font-semibold gap-5">
                    <!-- If this book is borrowed by the user   -->
                        {% if is_borrowed  %}
                            <!-- Due Date of the borrowed book  -->                        
                            <p>Due Date: {{ book_due_info }}</p>
                                <!-- If the current time  is less than or equal to one day more than the due_date    -->
                                {% if book_due_near %}
                                    <!-- It will show Alert that you have only 1 day left   -->
                                    <div class=" text-white font-bold text-2xl" style="color:#cc0000 !important"><p >Alert! You have only 1 day left to return this book.</p></div>
                                    <!-- Check comes the book_details view to check it is already requested for reissued or not  -->
                                    {% if not check %}
                                        <!-- If it is not requested for reissued we will show reissue option    -->
                                        <form method="post" action="{% url 'boipoka_app:reissue_book' book.pk %}">
                                            {% csrf_token %}
                                            <button type="submit" class=" px-3 py-2 text-white font-semibold" style="background-color: #1B4D3E !important;margin-left:50% !important;">Reissue Book</button>
                                        </form>
                                    <!-- If it is requested for reissued we wil show this message untill the admin extends the duedate -->
                                    {% else %}
                                        <button  class=" px-3 py-2 text-white font-semibold" style="background-color: #1B4D3E !important;margin-left:50% !important;">Your request for reissuing this book has been sent</button>
                                    {% endif %}
                            {% endif %}
                        {% endif %}
                </div>
            {% endif %}
            <button class="mt-5 px-6 py-2 bg-slate-700 text-white font-semibold" ><a href="{% url 'boipoka_app:book_list' %}">Back to Booklists</a></button>
        {% endif %}
    </div>
</div>

{% endblock %}

boipoka_app/templates/boipoka_app/index.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>{% block title %}Home{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% comment %} <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet"> {% endcomment %}
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
</head>
<!-- Bootstrap JS and dependencies (Popper.js and jQuery) -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 

<body class='bg-gray-900'>
{% block content %}
<div class="mt-5 flex flex-col justify-between  gap-12">
    <h1 class="mt-36 text-center text-3xl text-white content-center">Welcome to Boipoka</h1>
    <div class="flex content-center justify-between gap-6" style="left:20%;right:20%;margin:auto;">
        <a href="{% url 'boipoka_app:register' %}" class=" font-bold text-lg  px-5 py-3 rounded-xl  text-white bg-green-800 hover:bg-green-900 text-decoration-none">Register</a>
        <a href="{% url 'boipoka_app:login' %}" class="font-bold bg-purple-900 hover:bg-indigo-900 px-5 py-3 rounded-xl  text-white text-decoration-none">Log In</a>
    </div>
</div>

{% endblock %}
</body>